### ISSUE TITLE
Inventory Slot issues

### ISSUE THREAD

**Issue by BasilChristofis** [JarrydWorland/2021_Capstone_GP2_Team#47]
**Build Version**
v0.0.5

**Describe the bug**
When picking up an Item of the same type in the same slot, the swap spawns an invisible Item that can be picked up from any range, even across room borders. It also happens when all slots are full. Health ups can lock slots on use if they are the first Item picked up.

**To Reproduce**
Steps to reproduce the Item Slot behaviour:
1. Destroy enough enemies to get at least 2 items of the same type
2. Destroy enough enemies to get an item of the same type on the floor.
3. Shift the item on the floor with the item in the slot.

Steps to reproduce the Health Item behaviour:
1.Destroy enough enemies to get a health item first
2.get hit
3. use health item
4.see error

**Expected behaviour**
Items are expected to switch without spawning invisibly, and able to spawn only in range of the player.

**Screenshots**
![image](https://user-images.githubusercontent.com/42164170/120961250-c6dd0380-c7a0-11eb-8f55-1fb8105d9cd4.png)
![image](https://user-images.githubusercontent.com/42164170/120961734-b8431c00-c7a1-11eb-9bb9-cf84c1905600.png)
![image](https://user-images.githubusercontent.com/42164170/120962031-47503400-c7a2-11eb-8d7a-3ac8408010bf.png)

**Desktop (please complete the following information):**
 - Windows
 - Unity
 - 2020.2.2f

**Comment by 102113528** [comment]
Solved with the refactor.
